spring:
  datasource:
    username: root
    password: chenxp106
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://123.207.60.196:3307/myblog?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
mybatis:
  mapper-locations: mapper/*.xml
server:
  port: 8081
logging:
  level:
    cn.gdut.myblog.system.mapper: debug
#debug: true
